"""Fix float types in call_insights

Revision ID: 41acd627bdc8
Revises: 8567653d3517
Create Date: 2025-08-03 21:13:41.960344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41acd627bdc8'
down_revision: Union[str, Sequence[str], None] = '8567653d3517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_insights', 'agent_talk_ratio',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('call_insights', 'customer_sentiment_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_call_insights_id'), 'call_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_insights_id'), table_name='call_insights')
    op.alter_column('call_insights', 'customer_sentiment_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('call_insights', 'agent_talk_ratio',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
