"""Add call_insights table

Revision ID: 8567653d3517
Revises: 7ba3f4d60b65
Create Date: 2025-08-03 20:48:46.716268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8567653d3517'
down_revision: Union[str, Sequence[str], None] = '7ba3f4d60b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_insights',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('call_id', sa.String(), nullable=False, unique=True),
    sa.Column('agent_talk_ratio', sa.Integer(), nullable=True),
    sa.Column('customer_sentiment_score', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_insights')
    # ### end Alembic commands ###
